spring.application.name=ride-management-service

server.port=5002

spring.data.mongodb.uri=mongodb+srv://admin:Ride12@kuppi.lynqk8q.mongodb.net/?retryWrites=true&w=majority&appName=kuppi

spring.data.mongodb.database=ride_management_db

spring.mongodb.uri=${MONGODB_URI:mongodb+srv://admin:Ride12@kuppi.lynqk8q.mongodb.net/?retryWrites=true&w=majority&appName=kuppi}

spring.mongodb.database=${MONGODB_DATABASE:ride_management_db}

springdoc.swagger-ui.path=/swagger-ui.html